; spans.asm - per-radius horizontal span tables for the dot plotter.
; GENERATED by tools/stipple.py disc formula (dx*dx+dy*dy <= r*r);
; regenerate if the disc shape changes. Do not hand-edit.
;
; Each radius table is a list of (dy, dx, len) triplets ordered top->bottom,
; terminated by a triplet whose len byte is 0. dy/dx are signed (two's comp).

.spans_1
    EQUB 255,0,1    ; dy=-1 dx=0 len=1
    EQUB 0,255,3    ; dy=0 dx=-1 len=3
    EQUB 1,0,1    ; dy=1 dx=0 len=1
    EQUB 0,0,0    ; end

.spans_2
    EQUB 254,0,1    ; dy=-2 dx=0 len=1
    EQUB 255,255,3    ; dy=-1 dx=-1 len=3
    EQUB 0,254,5    ; dy=0 dx=-2 len=5
    EQUB 1,255,3    ; dy=1 dx=-1 len=3
    EQUB 2,0,1    ; dy=2 dx=0 len=1
    EQUB 0,0,0    ; end

.spans_3
    EQUB 253,0,1    ; dy=-3 dx=0 len=1
    EQUB 254,254,5    ; dy=-2 dx=-2 len=5
    EQUB 255,254,5    ; dy=-1 dx=-2 len=5
    EQUB 0,253,7    ; dy=0 dx=-3 len=7
    EQUB 1,254,5    ; dy=1 dx=-2 len=5
    EQUB 2,254,5    ; dy=2 dx=-2 len=5
    EQUB 3,0,1    ; dy=3 dx=0 len=1
    EQUB 0,0,0    ; end

.spans_4
    EQUB 252,0,1    ; dy=-4 dx=0 len=1
    EQUB 253,254,5    ; dy=-3 dx=-2 len=5
    EQUB 254,253,7    ; dy=-2 dx=-3 len=7
    EQUB 255,253,7    ; dy=-1 dx=-3 len=7
    EQUB 0,252,9    ; dy=0 dx=-4 len=9
    EQUB 1,253,7    ; dy=1 dx=-3 len=7
    EQUB 2,253,7    ; dy=2 dx=-3 len=7
    EQUB 3,254,5    ; dy=3 dx=-2 len=5
    EQUB 4,0,1    ; dy=4 dx=0 len=1
    EQUB 0,0,0    ; end

.spans_5
    EQUB 251,0,1    ; dy=-5 dx=0 len=1
    EQUB 252,253,7    ; dy=-4 dx=-3 len=7
    EQUB 253,252,9    ; dy=-3 dx=-4 len=9
    EQUB 254,252,9    ; dy=-2 dx=-4 len=9
    EQUB 255,252,9    ; dy=-1 dx=-4 len=9
    EQUB 0,251,11    ; dy=0 dx=-5 len=11
    EQUB 1,252,9    ; dy=1 dx=-4 len=9
    EQUB 2,252,9    ; dy=2 dx=-4 len=9
    EQUB 3,252,9    ; dy=3 dx=-4 len=9
    EQUB 4,253,7    ; dy=4 dx=-3 len=7
    EQUB 5,0,1    ; dy=5 dx=0 len=1
    EQUB 0,0,0    ; end

.spans_6
    EQUB 250,0,1    ; dy=-6 dx=0 len=1
    EQUB 251,253,7    ; dy=-5 dx=-3 len=7
    EQUB 252,252,9    ; dy=-4 dx=-4 len=9
    EQUB 253,251,11    ; dy=-3 dx=-5 len=11
    EQUB 254,251,11    ; dy=-2 dx=-5 len=11
    EQUB 255,251,11    ; dy=-1 dx=-5 len=11
    EQUB 0,250,13    ; dy=0 dx=-6 len=13
    EQUB 1,251,11    ; dy=1 dx=-5 len=11
    EQUB 2,251,11    ; dy=2 dx=-5 len=11
    EQUB 3,251,11    ; dy=3 dx=-5 len=11
    EQUB 4,252,9    ; dy=4 dx=-4 len=9
    EQUB 5,253,7    ; dy=5 dx=-3 len=7
    EQUB 6,0,1    ; dy=6 dx=0 len=1
    EQUB 0,0,0    ; end

.spans_7
    EQUB 249,0,1    ; dy=-7 dx=0 len=1
    EQUB 250,253,7    ; dy=-6 dx=-3 len=7
    EQUB 251,252,9    ; dy=-5 dx=-4 len=9
    EQUB 252,251,11    ; dy=-4 dx=-5 len=11
    EQUB 253,250,13    ; dy=-3 dx=-6 len=13
    EQUB 254,250,13    ; dy=-2 dx=-6 len=13
    EQUB 255,250,13    ; dy=-1 dx=-6 len=13
    EQUB 0,249,15    ; dy=0 dx=-7 len=15
    EQUB 1,250,13    ; dy=1 dx=-6 len=13
    EQUB 2,250,13    ; dy=2 dx=-6 len=13
    EQUB 3,250,13    ; dy=3 dx=-6 len=13
    EQUB 4,251,11    ; dy=4 dx=-5 len=11
    EQUB 5,252,9    ; dy=5 dx=-4 len=9
    EQUB 6,253,7    ; dy=6 dx=-3 len=7
    EQUB 7,0,1    ; dy=7 dx=0 len=1
    EQUB 0,0,0    ; end

.spanptr_lo
    EQUB 0, LO(spans_1), LO(spans_2), LO(spans_3), LO(spans_4), LO(spans_5), LO(spans_6), LO(spans_7)
.spanptr_hi
    EQUB 0, HI(spans_1), HI(spans_2), HI(spans_3), HI(spans_4), HI(spans_5), HI(spans_6), HI(spans_7)
