#!/usr/bin/env python3
"""Generate stipple256_bin.h by assembling bbc/stipple256.asm with beebasm
and emitting the raw 241-byte ROM as a C array.

Re-run this whenever bbc/stipple256.asm changes. The generated header is
committed to the repo so the 4k-emu build doesn't require beebasm out of
the box -- only when you intend to track upstream asm edits.
"""
import sys, pathlib, subprocess

repo = pathlib.Path(__file__).resolve().parent.parent
bbc = repo / "bbc"
asm = bbc / "stipple256.asm"
beebasm = repo / "tools" / "beebasm.exe"
raw_bin = bbc / "STIP256"                  # beebasm SAVE output without -do
dst = pathlib.Path(__file__).resolve().parent / "stipple256_bin.h"

if not asm.exists():
    sys.exit(f"missing {asm}")
if not beebasm.exists():
    sys.exit(f"missing {beebasm} -- download from https://github.com/stardot/beebasm")

# Invoke beebasm without -do so the SAVE directive writes STIP256 as a raw
# binary in the current directory.
subprocess.run([str(beebasm), "-i", str(asm)],
               cwd=str(bbc), check=True, stdout=subprocess.DEVNULL)

data = raw_bin.read_bytes()
lines = ["// generated by 4k-emu/bin_to_h.py -- do not edit", "",
         f"static const unsigned char kStipple256Bin[{len(data)}] = {{"]
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
lines += ["};",
          f"static const int kStipple256BinLen = {len(data)};",
          f"static const unsigned short kStipple256LoadAddr = 0x1900;",
          ""]
dst.write_text("\n".join(lines))
print(f"wrote {dst} ({len(data)} bytes)")
